#!/usr/bin/env bash

export WORKDIR=/Users/shuren
export WORKDIR=~/fun:$WORKDIR
export WORKDIR=~/fun/jupyter:$WORKDIR
export WORKDIR=~/hy:$WORKDIR
export WORKDIR=~/ras:$WORKDIR
export WORKDIR=~/.config/nvim:$WORKDIR
export WORKDIR=~/Documents/notes:$WORKDIR

if [[ $# -eq 1 ]]; then
    selected=$1
else
    workdirs=$(echo $WORKDIR | tr ':' ' ')
    selected=$(find $workdirs mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
