import = [
    "~/.config/alacritty/alacritty-theme/themes/tomorrow_night.toml"
]
[env]
TERM = "alacritty-direct"
[window]
dynamic_padding = true
[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "SemiBold" }
size = 12
[shell]
program = "/bin/bash"
args = ["-ilc", "setup-tmux;exec /bin/bash -il"]
