import = [
    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
]
[env]
TERM = "alacritty-direct"
[window]
option_as_alt = "Both"
decorations = "Buttonless"
dynamic_padding = true
startup_mode = "Maximized"
[keyboard]
bindings = [
  { key = "Key6", mods = "Control", chars = "\u001e" }
]
[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "SemiBold" }
size = 14
[shell]
program = "/opt/homebrew/bin/bash"
args = ["-ilc", "setup-tmux;exec /opt/homebrew/bin/bash -il"]
